##Import relevant libraries and the data file

In [688]:
import pandas as pd
import numpy as np

In [689]:
valDf = pd.read_csv('./naveenkumar_propertyfinderbd.csv')

##Sneak peek into the original data file

In [690]:
valDf.head()

added_on  \
0   Thu, Apr 6, 2023 7:49 PM   
1   Sun, Apr 9, 2023 9:21 AM   
2  Wed, Mar 22, 2023 8:42 AM   
3  Mon, Mar 20, 2023 5:55 AM   
4   Wed, Apr 5, 2023 5:50 AM   

                                             address  \
0          CHETONA TOWER, 274/4, Mirpur 60 fit road.   
1                                     Gulshan Avenue   
2  JCX TOWER,1136/A, Block-I, Level 5, Japan Stre...   
3                                     Gulshan Avenue   
4  Sardar Complex, 1 South komlapur. Motijheel, D...   

                                  area  \
0                        Mirpur, Dhaka   
1                Gulshan Avenue, Dhaka   
2  Bashundhara Residential Area, Dhaka   
3                Gulshan Avenue, Dhaka   
4                     Motijheel, Dhaka   

                                             details fire_exit    generator  \
0  Flat sale\nReady Flat 1000 / 1200 / 1400 Squar...       NaN          NaN   
1  Gulshan avenue is the most expensive and sough...       Yes          NaN   
2  Two Room Furnished Serviced Apartment RENT in ...       Yes  Full Backup   
3  Fully furnished 7000 sft office available for ...       Yes  Full Backup   
4                                         open space       NaN  Full Backup   

   gym                last_updated lift offered_floor  ... property_category  \
0  NaN    Sun, Apr 9, 2023 5:12 AM  NaN             5  ...       Residential   
1  NaN    Sun, Apr 9, 2023 9:21 AM  Yes             5  ...        Commercial   
2  NaN  Sat, Mar 25, 2023 10:26 AM  Yes             4  ...       Residential   
3  NaN   Mon, Mar 20, 2023 5:55 AM  Yes             7  ...        Commercial   
4  NaN   Sat, Apr 8, 2023 11:46 AM  NaN             1  ...        Commercial   

  property_id property_size      property_type  \
0         864          1200          Apartment   
1         875          2500       Office Space   
2         821           375  Service Apartment   
3         815          7000             Office   
4         856          9000      Factory Shade   

                                        property_url  rent_or_sale  \
0  https://propertyfinderbd.com/property-details/864          Sale   
1  https://propertyfinderbd.com/property-details/875          Rent   
2  https://propertyfinderbd.com/property-details/821          Rent   
3  https://propertyfinderbd.com/property-details/815          Rent   
4  https://propertyfinderbd.com/property-details/856          Rent   

  rooftop_garden swimming_pool  \
0            NaN           NaN   
1            Yes           NaN   
2            NaN           NaN   
3            Yes           NaN   
4            NaN           NaN   

                                               title total_bathrooms  
0  Ready Flat 1000 / 1200 / 1400 Square Feet Flat...               3  
1   2500 sft office space for rent in Gulshan Avenue             NaN  
2  Two Room Furnished Serviced Apartment RENT in ...               1  
3  Ready Fully furnished 7,000 sft office for ren...             NaN  
4                              Office space for rent              10  

[5 rows x 23 columns]

In [691]:
valDf.info()
valDf.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555 entries, 0 to 554
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   added_on           555 non-null    object
 1   address            555 non-null    object
 2   area               555 non-null    object
 3   details            555 non-null    object
 4   fire_exit          249 non-null    object
 5   generator          505 non-null    object
 6   gym                58 non-null     object
 7   last_updated       555 non-null    object
 8   lift               294 non-null    object
 9   offered_floor      491 non-null    object
 10  parking            396 non-null    object
 11  present_status     555 non-null    object
 12  price              555 non-null    object
 13  property_category  555 non-null    object
 14  property_id        555 non-null    int64 
 15  property_size      555 non-null    int64 
 16  property_type      555 non-null    object
 1

property_id  property_size
count   555.000000   5.550000e+02
mean    383.983784   2.539706e+04
std     239.644234   9.207220e+04
min      22.000000   0.000000e+00
25%     170.500000   1.362500e+03
50%     364.000000   3.000000e+03
75%     583.000000   1.591250e+04
max     875.000000   1.180800e+06

##Replace the original column names with the column names given as project standard

In [692]:
valDf.rename(columns = {'property_size':'AREA'}, inplace = True)
valDf.rename(columns = {'rent_or_sale':'PURPOSE'}, inplace = True)
#valDf.rename(columns = {'property_overview':'TITLE'}, inplace = True)
#valDf.rename(columns = {'property_description':'DETAILS'}, inplace = True)
valDf.rename(columns = {'property_category':'BUILDING_NATURE'}, inplace = True)
valDf.rename(columns = {'property_type':'BUILDING_TYPE'}, inplace = True)
#valDf.rename(columns = {'num_bath_rooms':'TOTAL_BATHROOMS'}, inplace = True)
#valDf.rename(columns = {'fire_exit':'K1'}, inplace = True)
##valDf.rename(columns = {'generator':'K2'}, inplace = True)
#valDf.rename(columns = {'gym':'K3'}, inplace = True)
#valDf.rename(columns = {'lift':'K4'}, inplace = True)
#valDf.rename(columns = {'offered_floor':'K5'}, inplace = True)
#valDf.rename(columns = {'parking':'parking-spaces-amenity'}, inplace = True)
#valDf.rename(columns = {'present_status':'K7'}, inplace = True)
#valDf.rename(columns = {'rooftop_garden':'K8'}, inplace = True)
#valDf.rename(columns = {'swimming_pool':'swimming-pool-amenity'}, inplace = True)

In [693]:
valDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555 entries, 0 to 554
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   added_on         555 non-null    object
 1   address          555 non-null    object
 2   area             555 non-null    object
 3   details          555 non-null    object
 4   fire_exit        249 non-null    object
 5   generator        505 non-null    object
 6   gym              58 non-null     object
 7   last_updated     555 non-null    object
 8   lift             294 non-null    object
 9   offered_floor    491 non-null    object
 10  parking          396 non-null    object
 11  present_status   555 non-null    object
 12  price            555 non-null    object
 13  BUILDING_NATURE  555 non-null    object
 14  property_id      555 non-null    int64 
 15  AREA             555 non-null    int64 
 16  BUILDING_TYPE    555 non-null    object
 17  property_url     555 non-null    ob

##Get the District, city data by splitting the area column
##Feeding the country column with default as Bangladesh

In [694]:
valDf['DISTRICT']=valDf['area'].str.split(',').str[0]
valDf['CITY']=valDf['area'].str.split(',').str[1]
valDf['OTHERZONEAREA']=valDf['address'].str.split(',').str[-1]
valDf['COUNTRY']='Bangladesh'
valDf.head()

added_on  \
0   Thu, Apr 6, 2023 7:49 PM   
1   Sun, Apr 9, 2023 9:21 AM   
2  Wed, Mar 22, 2023 8:42 AM   
3  Mon, Mar 20, 2023 5:55 AM   
4   Wed, Apr 5, 2023 5:50 AM   

                                             address  \
0          CHETONA TOWER, 274/4, Mirpur 60 fit road.   
1                                     Gulshan Avenue   
2  JCX TOWER,1136/A, Block-I, Level 5, Japan Stre...   
3                                     Gulshan Avenue   
4  Sardar Complex, 1 South komlapur. Motijheel, D...   

                                  area  \
0                        Mirpur, Dhaka   
1                Gulshan Avenue, Dhaka   
2  Bashundhara Residential Area, Dhaka   
3                Gulshan Avenue, Dhaka   
4                     Motijheel, Dhaka   

                                             details fire_exit    generator  \
0  Flat sale\nReady Flat 1000 / 1200 / 1400 Squar...       NaN          NaN   
1  Gulshan avenue is the most expensive and sough...       Yes          NaN   
2  Two Room Furnished Serviced Apartment RENT in ...       Yes  Full Backup   
3  Fully furnished 7000 sft office available for ...       Yes  Full Backup   
4                                         open space       NaN  Full Backup   

   gym                last_updated lift offered_floor  ...  \
0  NaN    Sun, Apr 9, 2023 5:12 AM  NaN             5  ...   
1  NaN    Sun, Apr 9, 2023 9:21 AM  Yes             5  ...   
2  NaN  Sat, Mar 25, 2023 10:26 AM  Yes             4  ...   
3  NaN   Mon, Mar 20, 2023 5:55 AM  Yes             7  ...   
4  NaN   Sat, Apr 8, 2023 11:46 AM  NaN             1  ...   

                                        property_url PURPOSE rooftop_garden  \
0  https://propertyfinderbd.com/property-details/864    Sale            NaN   
1  https://propertyfinderbd.com/property-details/875    Rent            Yes   
2  https://propertyfinderbd.com/property-details/821    Rent            NaN   
3  https://propertyfinderbd.com/property-details/815    Rent            Yes   
4  https://propertyfinderbd.com/property-details/856    Rent            NaN   

  swimming_pool                                              title  \
0           NaN  Ready Flat 1000 / 1200 / 1400 Square Feet Flat...   
1           NaN   2500 sft office space for rent in Gulshan Avenue   
2           NaN  Two Room Furnished Serviced Apartment RENT in ...   
3           NaN  Ready Fully furnished 7,000 sft office for ren...   
4           NaN                              Office space for rent   

   total_bathrooms                      DISTRICT    CITY  \
0                3                        Mirpur   Dhaka   
1              NaN                Gulshan Avenue   Dhaka   
2                1  Bashundhara Residential Area   Dhaka   
3              NaN                Gulshan Avenue   Dhaka   
4               10                     Motijheel   Dhaka   

          OTHERZONEAREA     COUNTRY  
0   Mirpur 60 fit road.  Bangladesh  
1        Gulshan Avenue  Bangladesh  
2       Bashundhara R/A  Bangladesh  
3        Gulshan Avenue  Bangladesh  
4                 Dhaka  Bangladesh  

[5 rows x 27 columns]

#Remove columns that are not needed

In [695]:
valDf=valDf.drop(['added_on','last_updated','present_status','property_url','address','area'],axis=1)

#Looking up unique values of the field to see if there are any null or junk values

In [696]:
valDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555 entries, 0 to 554
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   details          555 non-null    object
 1   fire_exit        249 non-null    object
 2   generator        505 non-null    object
 3   gym              58 non-null     object
 4   lift             294 non-null    object
 5   offered_floor    491 non-null    object
 6   parking          396 non-null    object
 7   price            555 non-null    object
 8   BUILDING_NATURE  555 non-null    object
 9   property_id      555 non-null    int64 
 10  AREA             555 non-null    int64 
 11  BUILDING_TYPE    555 non-null    object
 12  PURPOSE          555 non-null    object
 13  rooftop_garden   201 non-null    object
 14  swimming_pool    31 non-null     object
 15  title            555 non-null    object
 16  total_bathrooms  406 non-null    object
 17  DISTRICT         555 non-null    ob

In [697]:
valDf['rooftop_garden'].unique()

array([nan, 'Yes'], dtype=object)

In [698]:
valDf['swimming_pool'].unique()

array([nan, 'Yes'], dtype=object)

In [699]:
valDf['total_bathrooms'].unique()

array(['3', nan, '1', '10', '4', '2', '9', '6', '5', '7', '20+', '19',
       '15', '12', '17', '20', '18'], dtype=object)

In [700]:
valDf['DISTRICT'].unique()

array(['Mirpur', 'Gulshan Avenue', 'Bashundhara Residential Area',
       'Motijheel', 'Uttara', 'Gulshan', 'Baridhara', 'Savar',
       'Sonargoan', 'Keraniganj', 'Ashulia', 'Banani',
       'Dhaka City Bypass.', 'Khilgaon', 'Joydebpur',
       'Purbachal New Town', 'Lalmatia', 'Tarabo', 'Sirajganj', 'Gazipur',
       'Rupganj', 'Mohakhali', 'Bayazid Bostami Road',
       'Purbachal American City', 'Tejgaon', 'Shewrapara', 'Nikunja',
       'Tongi', 'Khilkhet', 'Pubail', 'Bhaluka', 'Farmgate', 'Narsingdi',
       'Gulshan One', 'Gulistan', 'Paribagh', 'Jatrabari', 'Adabar',
       'Dhaka Cantonment', 'Pallabi', 'Rangpur City Corporation',
       'Shyamoli', 'Kawran Bazar', 'Shanti Nagar', 'Uttar Khan',
       'Aftab Nagar', 'Niketan', 'Dhanmondi', 'Badda', 'Manikganj',
       'Demra', 'Rampura', 'Shitakunda', 'Dhaka Chittagong Highway',
       'Mohammadpur', 'Moulvibazar', 'Valuka', 'Baily Road',
       'Faridpur City', 'Netrokona', 'Sreepur', 'Boshila', 'Ghorashal',
       'Madhabadi

In [701]:
valDf['CITY'].unique()

array([' Dhaka', ' Narayanganj', ' Gazipur', ' Rupganj', ' Rajshahi',
       ' Chittagong', ' Kaliganj', ' Mymensingh', ' Rangpur', ' Sylhet',
       ' Narsingdi.', ' Khulna', ' Savar.'], dtype=object)

In [702]:
valDf['price'].unique()

array(['1.00 BDT', '160.00 BDT', '36000.00 BDT', '1050000.00 BDT',
       '500000.00 BDT', '4000000.00 BDT', '48000.00 BDT', '170000.00 BDT',
       '430000000.00 BDT', '150000.00 BDT', '4250000.00 BDT',
       '600000000.00 BDT', '3500.00 BDT', '25000.00 BDT', '88.00 BDT',
       '5000.00 BDT', '800000.00 BDT', '285000000.00 BDT', '60.00 BDT',
       '110000000.00 BDT', '200000000.00 BDT', '1125000.00 BDT',
       '400000000.00 BDT', '15000000.00 BDT', '62000000.00 BDT',
       '2000000.00 BDT', '180000000.00 BDT', '6000000.00 BDT',
       '230000.00 BDT', '35000.00 BDT', '34999.00 BDT', '275000.00 BDT',
       '85000.00 BDT', '0.00 BDT', '120.00 BDT', '2017500.00 BDT',
       '4600.00 BDT', '900000000.00 BDT', '28000000.00 BDT',
       '11000000.00 BDT', '60000000.00 BDT', '1000000.00 BDT',
       '65000000.00 BDT', '75000000.00 BDT', '180000.00 BDT',
       '35000000.00 BDT', '7500000.00 BDT', '300000.00 BDT',
       '110000.00 BDT', '55000.00 BDT', '770000.00 BDT', '28.00 BDT',
   

In [703]:
valDf['AREA'].unique()

array([   1200,    2500,     375,    7000,    9000,   25000,    4600,
           800,    3200,    4000,    5400,       5,      20,    1550,
          2800,      16,     948,       8,      15,    1400,       4,
            10,    6500,    1089,  144000,   41000,   30000,   40510,
           150,    3000,       1,    6000,   11000,    3100,   93500,
          3017,    1345,   10500,  288000,    2160,    2100,   86400,
         43200,      11,   14400,      25,       3,      12,    8000,
           875,   22000,   16000,    7400,   36000,      52,   27500,
       1180800,  604800,   39600,     750,   14000,    3750,   17000,
          1650,    1800,  331200,    2200,       2,    1500,    1600,
        108000,    4200,     420,    4100,  148363,    6336,     166,
          2000,    1300,       9,   21000,   15000,    1662,    1000,
         47520,    1050,    2818,      59,    1140,    1700,   10000,
        244800,    1250,  100800,   93600,    4900,    7200,  417600,
          3500,     

In [704]:
valDf['fire_exit'].unique()

array([nan, 'Yes'], dtype=object)

In [705]:
valDf['generator'].unique()

array([nan, 'Full Backup', 'No', 'Partial'], dtype=object)

In [706]:
valDf['gym'].unique()

array([nan, 'Yes'], dtype=object)

In [707]:
valDf['lift'].unique()

array([nan, 'Yes'], dtype=object)

In [708]:
valDf['offered_floor'].unique()

array(['5', '4', '7', '1', nan, '3', '9', '2', '6', '18', '19', '11',
       '17', '10', '30+', '16', '12', '15', '13'], dtype=object)

In [709]:
valDf['parking'].unique()

array([nan, '2 Slot', '1 Slot', '4 Slot', '20 Slot', '5 Slot', '7 Slot',
       '3 Slot', '6 Slot', 'N/A Slot', '8 Slot', '১ Slot', '10+ Slot',
       '10 Slot', '50 Slot', '28 Slot',
       '2 level of basement Parking Slot', '14 Slot', '12 Slot',
       '20+ Slot', '5/7 Slot', '1216 Slot', '37 Slot'], dtype=object)

In [710]:
valDf['BUILDING_NATURE'].unique()

array(['Residential', 'Commercial', 'Land', 'None'], dtype=object)

In [711]:
valDf['BUILDING_TYPE'].unique()

array(['Apartment', 'Office Space', 'Service Apartment', 'Office',
       'Factory Shade', 'Commercial Plot', 'Commercial Building',
       'Industrial Plot', 'Ready Flat', 'Plot', 'Building', 'House',
       'Open Field', 'Factory Land', 'High Land', 'Factory Building',
       'Factory Sale', 'Apartment Office', 'Warehouse',
       'Building For Office', 'Furnished', 'Floor', 'Land with building',
       'Office Building', 'Brand New Apartment', 'Show-room',
       'Duplex House', 'None', 'Resorts / Banglobari', 'Duplex Apartment',
       'Open Floor', 'Semi Commercial Apartment'], dtype=object)

In [712]:
valDf['PURPOSE'].unique()

array(['Sale', 'Rent'], dtype=object)

In [713]:
valDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555 entries, 0 to 554
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   details          555 non-null    object
 1   fire_exit        249 non-null    object
 2   generator        505 non-null    object
 3   gym              58 non-null     object
 4   lift             294 non-null    object
 5   offered_floor    491 non-null    object
 6   parking          396 non-null    object
 7   price            555 non-null    object
 8   BUILDING_NATURE  555 non-null    object
 9   property_id      555 non-null    int64 
 10  AREA             555 non-null    int64 
 11  BUILDING_TYPE    555 non-null    object
 12  PURPOSE          555 non-null    object
 13  rooftop_garden   201 non-null    object
 14  swimming_pool    31 non-null     object
 15  title            555 non-null    object
 16  total_bathrooms  406 non-null    object
 17  DISTRICT         555 non-null    ob

#Cleaning
###nan values
###remove unit BDT from price
###remove Slot from parking
###data types for numeric fields


##Fill NaN values

In [714]:
valDf = valDf.replace(np.nan, '', regex=True)
valDf.head(2)

details fire_exit generator gym  \
0  Flat sale\nReady Flat 1000 / 1200 / 1400 Squar...                           
1  Gulshan avenue is the most expensive and sough...       Yes                 

  lift offered_floor parking       price BUILDING_NATURE  property_id  ...  \
0                  5            1.00 BDT     Residential          864  ...   
1  Yes             5  2 Slot  160.00 BDT      Commercial          875  ...   

   BUILDING_TYPE PURPOSE rooftop_garden swimming_pool  \
0      Apartment    Sale                                
1   Office Space    Rent            Yes                 

                                               title total_bathrooms  \
0  Ready Flat 1000 / 1200 / 1400 Square Feet Flat...               3   
1   2500 sft office space for rent in Gulshan Avenue                   

         DISTRICT    CITY         OTHERZONEAREA     COUNTRY  
0          Mirpur   Dhaka   Mirpur 60 fit road.  Bangladesh  
1  Gulshan Avenue   Dhaka        Gulshan Avenue  Bangladesh  

[2 rows x 21 columns]

##Remove Unit from Price

In [715]:
valDf['price']=valDf['price'].apply(lambda x: x.split(" ")[0] )
valDf['price'].unique()

array(['1.00', '160.00', '36000.00', '1050000.00', '500000.00',
       '4000000.00', '48000.00', '170000.00', '430000000.00', '150000.00',
       '4250000.00', '600000000.00', '3500.00', '25000.00', '88.00',
       '5000.00', '800000.00', '285000000.00', '60.00', '110000000.00',
       '200000000.00', '1125000.00', '400000000.00', '15000000.00',
       '62000000.00', '2000000.00', '180000000.00', '6000000.00',
       '230000.00', '35000.00', '34999.00', '275000.00', '85000.00',
       '0.00', '120.00', '2017500.00', '4600.00', '900000000.00',
       '28000000.00', '11000000.00', '60000000.00', '1000000.00',
       '65000000.00', '75000000.00', '180000.00', '35000000.00',
       '7500000.00', '300000.00', '110000.00', '55000.00', '770000.00',
       '28.00', '140.00', '45000000.00', '61500000.00', '57000000.00',
       '3500000.00', '14175000.00', '2050000000.00', '1344000000.00',
       '10000.00', '22000000.00', '280000.00', '415500.00', '1600000.00',
       '215000.00', '130.00', '70

##Remove Slot from parking

In [716]:
valDf["parking"]=valDf["parking"].str.replace("10+ Slot", "10")
valDf["parking"]=valDf["parking"].str.replace("20+ Slot", "20")
valDf["parking"]=valDf["parking"].str.replace("Slot", "")
valDf["parking"]=valDf["parking"].str.replace("N/A", "0")
valDf["parking"]=valDf["parking"].str.replace("2 level of basement Parking", "2")
valDf["parking"]=valDf["parking"].str.replace("১ ", "1")
valDf["parking"]=valDf["parking"].str.replace("5/7", "5")


<ipython-input-716-13d205ec2e92>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  valDf["parking"]=valDf["parking"].str.replace("10+ Slot", "10")
<ipython-input-716-13d205ec2e92>:2: FutureWarning: The default value of regex will change from True to False in a future version.
  valDf["parking"]=valDf["parking"].str.replace("20+ Slot", "20")


In [717]:
valDf['price'].dtype

dtype('O')

In [718]:
valDf['parking'].unique()

array(['', '2 ', '1 ', '4 ', '20', '5 ', '7 ', '3 ', '6 ', '0 ', '8 ',
       '1', '10+ ', '10', '50 ', '28 ', '14 ', '12 ', '20+ ', '1216 ',
       '37 '], dtype=object)

In [719]:
valDf.head()

details fire_exit    generator  \
0  Flat sale\nReady Flat 1000 / 1200 / 1400 Squar...                          
1  Gulshan avenue is the most expensive and sough...       Yes                
2  Two Room Furnished Serviced Apartment RENT in ...       Yes  Full Backup   
3  Fully furnished 7000 sft office available for ...       Yes  Full Backup   
4                                         open space            Full Backup   

  gym lift offered_floor parking       price BUILDING_NATURE  property_id  \
0                      5                1.00     Residential          864   
1      Yes             5      2       160.00      Commercial          875   
2      Yes             4      1     36000.00     Residential          821   
3      Yes             7      4   1050000.00      Commercial          815   
4                      1      2    500000.00      Commercial          856   

   ...      BUILDING_TYPE PURPOSE rooftop_garden swimming_pool  \
0  ...          Apartment    Sale                                
1  ...       Office Space    Rent            Yes                 
2  ...  Service Apartment    Rent                                
3  ...             Office    Rent            Yes                 
4  ...      Factory Shade    Rent                                

                                               title total_bathrooms  \
0  Ready Flat 1000 / 1200 / 1400 Square Feet Flat...               3   
1   2500 sft office space for rent in Gulshan Avenue                   
2  Two Room Furnished Serviced Apartment RENT in ...               1   
3  Ready Fully furnished 7,000 sft office for ren...                   
4                              Office space for rent              10   

                       DISTRICT    CITY         OTHERZONEAREA     COUNTRY  
0                        Mirpur   Dhaka   Mirpur 60 fit road.  Bangladesh  
1                Gulshan Avenue   Dhaka        Gulshan Avenue  Bangladesh  
2  Bashundhara Residential Area   Dhaka       Bashundhara R/A  Bangladesh  
3                Gulshan Avenue   Dhaka        Gulshan Avenue  Bangladesh  
4                     Motijheel   Dhaka                 Dhaka  Bangladesh  

[5 rows x 21 columns]

##Fix the data types for numeric columns

In [720]:
valDf[['price','AREA']] = valDf[['price','AREA']].apply(pd.to_numeric)

In [721]:
valDf[['parking','offered_floor','total_bathrooms']] = valDf[['parking','offered_floor','total_bathrooms']].apply(pd.to_numeric)

ValueError: ignored

In [ ]:
valDf.info()

In [722]:
valDf.to_csv('./naveenkumar_propertyfinderbd_cleaned.csv', index=False)